name: Non Containerized Unit Tests
on: [push, pull_request]

jobs:
  run-nc-unit-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Run Non Containerized Test
        run: |
          make run-nc-tests
