name: Unit Tests with Postgres

# Run on each new PR and each new push to existing PR
on: [push, pull_request]

jobs:
  run-unit-tests-postgres:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0

      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Unit Tests with Postgres
        id: run-test-postgres
        run: make test-postgres || exit 1
